version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: suprss
      POSTGRES_USER: suprss
      POSTGRES_PASSWORD: suprss
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  server:
    build: ./server
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://suprss:suprss@db:5432/suprss?schema=public
      JWT_SECRET: a5688a6770a1011fa331985c7439a1c64321678fc4dcaf42a62aa34779827804f7a5d7a0e9d9f864a51eb17ea34c8e35c578d06829a00a188ed34f7b7d75262b
      CORS_ORIGIN: http://localhost:5173
      NODE_ENV: production
    ports:
      - "8080:8080"
      - "5555:5555"

  client:
    image: nginx:alpine   # placeholder (on branchera le vrai client plus tard)
    ports:
      - "5173:80"
    command: ["/bin/sh","-c","while true; do sleep 3600; done"]

volumes:
  db_data:
